## Notebook 3

### On this notebook we are going to organize the dataframe in a MultIndex dataframe

In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('Players Wikipedia.csv',index_col = 0)

In [16]:
df.head()

       Worldcup     Team                Player  Day  Month  Year
0  1930 Uruguay  Bolivia  Luis Reyes Penaranda    5      6  1911
1  1930 Uruguay  Bolivia           Juan Argote    6      1  1907
2  1930 Uruguay  Bolivia          Miguel Brito   13      6  1901
3  1930 Uruguay  Bolivia         Diógenes Lara    6      4  1903
4  1930 Uruguay  Bolivia         Mario Alborta   19      9  1910

In [17]:
worldcups =  ['1930 Uruguay','1934 Italy', '1938 France', '1950 Brazil', '1954 Switzerland','1958 Sweden','1962 Chile','1970 Mexico','1982 Spain']

We going to slice the imported dataframe in tiny peaces for each team of each worldcup as below

In [18]:
filtering = df['Worldcup'] == '1930 Uruguay'
filtering2 = df['Team'] == 'Bolivia'
df5 = df[filtering][filtering2]

C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3273977635.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df5 = df[filtering][filtering2]

In [19]:
df5

       Worldcup     Team                Player  Day  Month  Year
0  1930 Uruguay  Bolivia  Luis Reyes Penaranda    5      6  1911
1  1930 Uruguay  Bolivia           Juan Argote    6      1  1907
2  1930 Uruguay  Bolivia          Miguel Brito   13      6  1901
3  1930 Uruguay  Bolivia         Diógenes Lara    6      4  1903
4  1930 Uruguay  Bolivia         Mario Alborta   19      9  1910
5  1930 Uruguay  Bolivia       José Bustamante    1      1  1907
6  1930 Uruguay  Bolivia        René Fernández    1      1  1906
7  1930 Uruguay  Bolivia         Rafael Mendez    1      1  1904

The function below will do it and some more adjusts:

In [20]:
def organize_team(df,team_name,worldcup_name):
    #df - DataFrame of shape (n,6), n - name of players
    filtering = df['Worldcup'] == worldcup_name
    filtering2 = df['Team'] == team_name
    df2 = df[filtering][filtering2]
    df2 = df2.iloc[:,2:].T
    df2 = df2.reset_index().reset_index()
    df2.columns = range(df2.shape[1])
    df2 = df2.reset_index()
    df2.columns = range(df2.shape[1])
    df2.iloc[:,0] = worldcup_name
    df2.iloc[:,1] = team_name
    return df2

We going to use this format above for each team and concat the obtained dataframes vertically in a bigger dataframe

In [21]:
dfx = pd.DataFrame()
for worldcup in worldcups:
    teams = df[df['Worldcup'] == worldcup]['Team'].unique() #Teams from the iterated worldcup
    for team in teams:
        df2 = organize_team(df,team,worldcup)
        #df2.index = range(df2.shape[1])
        dfx = pd.concat((dfx,df2))

C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]
C:\Users\italo\AppData\Local\Temp\ipykernel_12604\3246399513.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df[filtering][filtering2]

In [22]:
dfx.head(8)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1930 Uruguay,Bolivia,Player,Luis Reyes Penaranda,Juan Argote,Miguel Brito,Diógenes Lara,Mario Alborta,José Bustamante,René Fernández,Rafael Mendez,NaN,NaN,NaN
1,1930 Uruguay,Bolivia,Day,5,6,13,6,19,1,1,1,NaN,NaN,NaN
2,1930 Uruguay,Bolivia,Month,6,1,6,4,9,1,1,1,NaN,NaN,NaN
3,1930 Uruguay,Bolivia,Year,1911,1907,1901,1903,1910,1907,1906,1904,NaN,NaN,NaN
0,1930 Uruguay,Mexico,Player,Isidoro Sota,Francisco Gutiérrez,Alfredo Sanchez,Roberto Gayon,Felipe Olivares,Jose Ruiz,NaN,NaN,NaN,NaN,NaN
1,1930 Uruguay,Mexico,Day,4,14,28,1,5,1,NaN,NaN,NaN,NaN,NaN
2,1930 Uruguay,Mexico,Month,2,3,5,1,2,1,NaN,NaN,NaN,NaN,NaN
3,1930 Uruguay,Mexico,Year,1902,1904,1904,1905,1910,1904,NaN,NaN,NaN,NaN,NaN

In [23]:
dfx.index = range(dfx.shape[0])
dfx = dfx.fillna(0)
dfx.index = pd.MultiIndex.from_frame(dfx.iloc[:,:2])
dfx.head()

                                0        1       2                     3   \
0            1
1930 Uruguay Bolivia  1930 Uruguay  Bolivia  Player  Luis Reyes Penaranda
             Bolivia  1930 Uruguay  Bolivia     Day                     5
             Bolivia  1930 Uruguay  Bolivia   Month                     6
             Bolivia  1930 Uruguay  Bolivia    Year                  1911
             Mexico   1930 Uruguay   Mexico  Player          Isidoro Sota

                                       4                5              6   \
0            1
1930 Uruguay Bolivia          Juan Argote     Miguel Brito  Diógenes Lara
             Bolivia                    6               13              6
             Bolivia                    1                6              4
             Bolivia                 1907             1901           1903
             Mexico   Francisco Gutiérrez  Alfredo Sanchez  Roberto Gayon

                                   7                8               9   \
0            1
1930 Uruguay Bolivia    Mario Alborta  José Bustamante  René Fernández
             Bolivia               19                1               1
             Bolivia                9                1               1
             Bolivia             1910             1907            1906
             Mexico   Felipe Olivares        Jose Ruiz               0

                                 10 11 12 13
0            1
1930 Uruguay Bolivia  Rafael Mendez  0  0  0
             Bolivia              1  0  0  0
             Bolivia              1  0  0  0
             Bolivia           1904  0  0  0
             Mexico               0  0  0  0

In [24]:
dfx = dfx.iloc[:,2:]
dfy = dfx.T
dfy.head()

0          1930 Uruguay                                                      \
1               Bolivia Bolivia Bolivia Bolivia               Mexico Mexico
2                Player     Day   Month    Year               Player    Day
3  Luis Reyes Penaranda       5       6    1911         Isidoro Sota      4
4           Juan Argote       6       1    1907  Francisco Gutiérrez     14
5          Miguel Brito      13       6    1901      Alfredo Sanchez     28
6         Diógenes Lara       6       4    1903        Roberto Gayon      1

0                                            ... 1970 Mexico          \
1 Mexico Mexico           Paraguay Paraguay  ...     Morocco Morocco
2  Month   Year             Player      Day  ...       Month    Year
3      2   1902      Modesto Denis        9  ...           2    1941
4      3   1904    Salvador Flores        1  ...          11    1947
5      5   1904  Francisco Aguirre       30  ...           0       0
6      1   1905   Santiago Benitez        1  ...           0       0

0                                         1982 Spain
1           Peru Peru   Peru  Peru            Kuwait Kuwait Kuwait Kuwait
2         Player  Day  Month  Year            Player    Day  Month   Year
3  Ruben Correra   25      7  1941    Mohammed Ahmad      1      1   1955
4              0    0      0     0  Nasser Al-Ghanem      4      4   1961
5              0    0      0     0   Mubarak Al-Issa      1      1   1961
6              0    0      0     0                 0      0      0      0

[5 rows x 136 columns]

<b>Checking that we still with 100 players at the end:</b>

In [25]:
n_players = 0
for worldcup in worldcups:
    teams = df[df['Worldcup'] == worldcup]['Team'].unique()
    for team in teams:
        n_players += (dfy[worldcup][team].iloc[1:,0] !=0).value_counts()[True]

In [26]:
n_players

100